version: '3.8'

services:
  frontend:
    build: ./FINANCETRACKER_FRONTEND
    volumes:
      - /mnt/c/Users/tahah/OneDrive/Desktop/FinanceTracker-Frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./FINANCETRACKER_BACKEND
    volumes:
      - /mnt/c/Users/tahah/OneDrive/Desktop/FinanceTracker-Backend:/app
    ports:
      - "8080:8080"
    env_file:
      - /mnt/c/Users/tahah/OneDrive/Desktop/FINANCETRACKER_BACKEND/.env
    depends_on:
      - db

networks:
  default:
    driver: bridge
